### ISSUE TITLE
Minor issue : logs for weights never happen 

### ISSUE THREAD

**Issue by umarteauowkin** [owkin/FLamby#233]
https://github.com/owkin/FLamby/blob/1126e7d61cce87f2cab25e8224a43a515b8bb511/flamby/strategies/utils.py#L287-L294

maybe since the log frequence is not done in terms of epochs, these should be logged in terms of "partial epochs"

**Comment by jeandut** [comment]
@umarteauowkin, just to be sure to understand: there is no actual bug in the code right ? Logging does happen every local epochs, however you would like to change the frequency as you are not doing enough epochs each round ?

**Comment by umarteauowkin** [comment]
There is no bug per se, but I forgot one line. The original code is this one : 

                if _batch % self.log_period == 0:
                    if _current_epoch > self.current_epoch:
                        # At each epoch we look at the histograms of all the
                        # network's parameters
                        for name, p in self.model.named_parameters():
                            self.writer.add_histogram(
                                f"client{self.client_id}/{name}", p, _current_epoch
                            )

The thing is the chances of the _current_epoch > self.current_epoch (which only happens for one update every epoch) and _batch % self.log_period == 0 being true together are very weak. The second if should be put out of the the first one for instance, or the parameters logged in the histogram at every log period.

**Comment by jeandut** [comment]
You are right, the double condition is indeed too strong, I would call that a bug even a slight one. Let's fix it.

**Comment by jeandut** [comment]
Solved by #247
